### ISSUE TITLE
Illegal access error

### ISSUE THREAD

**Issue by kshitij91** [allegro/solr-fast-collapsing-query-parser#2]
Tried using the plugin but it gives Illegal access error saying:
<img width="1311" alt="Screenshot 2020-07-28 at 4 48 01 PM" src="https://user-images.githubusercontent.com/40487554/88659217-52522680-d0f2-11ea-97e6-a502fe37a77b.png">

Caused by:
java.lang.IllegalAccessError: tried to access class org.apache.lucene.search.MultiLeafFieldComparator from class org.apache.lucene.search.FastCollapsingQueryFilter$1
	at org.apache.lucene.search.FastCollapsingQueryFilter$1.initContextComparators(FastCollapsingQueryFilter.java:90)
	at org.apache.lucene.search.FastCollapsingQueryFilter$1.doSetNextReader(FastCollapsingQueryFilter.java:80)
	at org.apache.lucene.search.SimpleCollector.getLeafCollector(SimpleCollector.java:33)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:647)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:442)
	at org.apache.solr.search.SolrIndexSearcher.buildAndRunCollectorChain(SolrIndexSearcher.java:203)
	at org.apache.solr.search.SolrIndexSearcher.getDocListNC(SolrIndexSearcher.java:1617)
	at org.apache.solr.search.SolrIndexSearcher.getDocListC(SolrIndexSearcher.java:1433)
	at org.apache.solr.search.SolrIndexSearcher.search(SolrIndexSearcher.java:580)
	at org.apache.solr.handler.component.QueryComponent.doProcessUngroupedSearch(QueryComponent.java:1485)
	at org.apache.solr.handler.component.QueryComponent.process(QueryComponent.java:398)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:313)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:198)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2576)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:803)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:582)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:424)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:351)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)

**Comment by kshitij91** [comment]
@awislowski I am seeing this error when applying external sort parameter while using this plugin, I was wondering if this is a potential bug in the plugin as of now?

**Comment by awislowski** [comment]
@kshitij91 could you give me this request and your solr version and info whether it is cloud or standalone instalation?

**Comment by kshitij91** [comment]
@awislowski sorry for the delayed reply, so solr version is '8.3.0' and we are running on solr cloud using collapse query.
Request is something like this:

1. this does not work as it is having external sort parameter:
http://localhost:8080/solr/core_name/select?sort=popularityVal%20desc%2CnewStore%20asc&q=*%3A*&indent=true&fq=%7B!fastCollapse%20field%3Dvariant_hash%20cost%3D300%20sort%3D%27Stock%20desc%2Cpopularity%20desc%7D&fl=*&echoParams=all&debugQuery=true&debug.explain.structured=true&!cache=false

2. This works fine when we remove external sort parameter:
http://localhost:8080/solr/core_name/select?q=*%3A*&indent=true&fq=%7B!fastCollapse%20field%3Dvariant_hash%20cost%3D300%20sort%3D%27Stock%20desc%2Cpopularity%20desc%7D&fl=*&echoParams=all&debugQuery=true&debug.explain.structured=true&!cache=false

let me know if you require any other information, thanks!

**Comment by awislowski** [comment]
I have upgraded plugin to Solr 8.6+. In this version external sort parameter does work properly.
Thanks for your contibution
